services:
  ai-persona-mongo:
    image: mongo
    container_name: ai-persona-mongo
    environment:
      MONGO_INITDB_DATABASE: ai-persona-mongo
    ports:
      - '27017:27017'
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    extends:
      file: docker-common.yaml
      service: ai-persona-mongo-network-service

  redis:
    image: redis
    container_name: ai-persona-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      timeout: 10s
      retries: 10
    extends:
      file: docker-common.yaml
      service: ai-persona-mongo-network-service

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: ai-persona-keycloak
    ports:
      - "7080:8080"
    volumes:
      - ./keycloak-bkp:/opt/keycloak/data
      - ./keycloak-theme:/opt/keycloak/themes
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev --import-realm"
    extends:
      file: docker-common.yaml
      service: ai-persona-mongo-network-service


networks:
  ai-persona-mongo-network:
    driver: "bridge"