services:
  ai-persona-mongo:
    image: mongo
    container_name: ai-persona-mongo
    environment:
      MONGO_INITDB_DATABASE: ai-persona-mongo
    ports:
      - '27017:27017'
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - ai-persona-mongo-network

  redis:
    image: redis
    container_name: ai-persona-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      timeout: 10s
      retries: 10
    networks:
      - ai-persona-mongo-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: ai-persona-keycloak
    ports:
      - "7080:8080"
    volumes:
      - ./keycloak-bkp:/opt/keycloak/data
      - ./keycloak-theme:/opt/keycloak/themes
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    networks:
      - ai-persona-mongo-network

  ai-persona-discovery-server:
    container_name: ai-persona-discovery-server
    image: amitking2309/ai-persona-discovery-server
    ports:
      - "8761:8761"
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 10s
    networks:
      - ai-persona-mongo-network

  ai-persona-profiles-conversation:
    container_name: ai-persona-profiles-conversation
    image: amitking2309/ai-persona-profiles-conversation
    ports:
      - "8081:8081"
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 10s
    environment:
      SPRING_DATA_MONGODB_DATABASE: "ai-persona-mongo"
      SPRING_DATA_MONGODB_HOST: "ai-persona-mongo"
      SPRING_DATA_MONGODB_POST: "27017"
      MACHINE_URL: ${MACHINE_URL}
      SPRING_AI_OLLAMA_BASE-URL: http://host.docker.internal:11434
      STABILITY_AI: http://host.docker.internal:7860/sdapi/v1/txt2img
      STABILITY_QUALITY: 30
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://ai-persona-discovery-server:8761/eureka/
      IMAGE_DIR: /images
    command: sh -c "chmod -R 777 /images"
    volumes:
      - ./images-data:/images
    depends_on:
      ai-persona-discovery-server:
        condition: service_healthy
      ai-persona-mongo:
        condition: service_healthy
    networks:
      - ai-persona-mongo-network

  ai-persona-gateway-server:
    container_name: ai-persona-gateway-server
    image: amitking2309/ai-persona-gateway-server
    ports:
      - "8080:8080"
    environment:
      MACHINE_URL: ${MACHINE_URL}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://ai-persona-discovery-server:8761/eureka/
      IMAGE_DIR: /images
    command: sh -c "chmod -R 777 /images"
    volumes:
      - ./images-data:/images
    depends_on:
      ai-persona-profiles-conversation:
        condition: service_healthy
    networks:
      - ai-persona-mongo-network

  ai-persona-frontend:
    container_name: ai-persona-frontend
    image: amitking2309/ai-persona-frontend
    ports:
      - "5173:80"
    networks:
      - ai-persona-mongo-network

networks:
  ai-persona-mongo-network:
    driver: "bridge"