server:
  port: 8081
spring:
  application:
    name: profiles-conversation
  data:
    mongodb:
      database: ai-persona-mongo
      host: localhost
      port: 27017

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://${machine_url}:7080/realms/ai-persona-hub/protocol/openid-connect/certs"

  #Ollama
  ai:
    ollama:
      base-url: http://${machine_url}:11434
      chat:
        options:
          temperature: 0.7
          model: llama3.1:latest #mistral

keycloak_url: http://${machine_url}:7080

machine_url: localhost

image:
  dir: /generated-images
stability:
  ai: http://${machine_url}:7860/sdapi/v1/txt2img
  quality: 30 # Higher value is good. Up to 50


logging:
  level:
    root: ERROR
    org:
      springframework:
        data:
          mongodb: ERROR
        boot: INFO

#Actuator with readiness and liveness
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

#For service discovery
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${machine_url}:8761/eureka/