server:
  port: 8081
spring:
  application:
    name: profiles-conversation
  data:
    mongodb:
      database: ai-persona-mongo
      host: localhost
      port: 27017

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "${machine_url}:7080/realms/ai-persona-hub/protocol/openid-connect/certs"

  #Ollama
  ai:
    ollama:
      base-url: ${machine_url}:11434
      chat:
        options:
          temperature: 0.7
          model: llama3.1:latest #mistral

keycloak_url: ${machine_url}:7080

machine_url: http://localhost

image:
  dir: /generated-images
stability:
  ai: ${machine_url}/sdapi/v1/txt2img
  quality: 30 # Higher value is good. Up to 50


#logging:
#  level:
#    org:
#      springframework:
#        data:
#          mongodb: DEBUG

#Actuator with readiness and liveness
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

#For service discovery
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${machine_url}:8761/eureka/