import * as React from 'react';
import { styled } from '@mui/material/styles';
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import Paper from '@mui/material/Paper';
import Fab from '@mui/material/Fab';
import List from '@mui/material/List';
import ListItemButton from '@mui/material/ListItemButton';
import ListItemAvatar from '@mui/material/ListItemAvatar';
import ListItemText from '@mui/material/ListItemText';
import ListSubheader from '@mui/material/ListSubheader';
import Avatar from '@mui/material/Avatar';
import MenuIcon from '@mui/icons-material/Menu';
import AddIcon from '@mui/icons-material/Add';
import SearchIcon from '@mui/icons-material/Search';
import MoreIcon from '@mui/icons-material/MoreVert';
import AppBarTop from "./AppBarTop"
import { Card, CardContent, CardHeader, Tooltip } from '@mui/material';
import { Chat } from '@mui/icons-material';
import { useNavigate } from 'react-router-dom';

export default function FriendList() {
    const navigate = useNavigate();
    const messages = [
        {
            id: 1,
            primary: 'Brunch this week?',
            secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
            person: '/static/images/avatar/5.jpg',
        },
        {
            id: 2,
            primary: 'Birthday Gift',
            secondary: `Do you have a suggestion for a good present for John on his work
            anniversary. I am really confused & would love your thoughts on it.`,
            person: '/static/images/avatar/1.jpg',
        },
        {
            id: 3,
            primary: 'Recipe to try',
            secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
            person: '/static/images/avatar/2.jpg',
        },
        {
            id: 4,
            primary: 'Yes!',
            secondary: 'I have the tickets to the ReactConf for this year.',
            person: '/static/images/avatar/3.jpg',
        },
        {
            id: 5,
            primary: "Doctor's Appointment",
            secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
            person: '/static/images/avatar/4.jpg',
        },
        {
            id: 6,
            primary: 'Discussion',
            secondary: `Menus that are generated by the bottom app bar (such as a bottom
            navigation drawer or overflow menu) open as bottom sheets at a higher elevation
            than the bar.`,
            person: '/static/images/avatar/5.jpg',
        },
        {
            id: 7,
            primary: 'Summer BBQ',
            secondary: `Who wants to have a cookout this weekend? I just got some furniture
            for my backyard and would love to fire up the grill.`,
            person: '/static/images/avatar/1.jpg',
        },
        {
            id: 9,
            primary: 'More elements',
            secondary: `lorum ispum.`,
            person: '/static/images/avatar/1.jpg',
        },
        {
            id: 10,
            primary: 'Some More elements',
            secondary: `nostrud exercitation `,
            person: '/static/images/avatar/1.jpg',
        },
    ];

    const goToChat = () => {
        navigate('/chat', { state: { data: 'example data' } });
    };

    return (
        <React.Fragment>
            <AppBarTop />
            <Paper square sx={{
                width: 650, display: 'flex',
                flexDirection: 'column', mt: 1,
                overflowY: 'auto',
                maxHeight: '80vh',
                scrollBehavior: 'smooth',
                '&::-webkit-scrollbar': {
                    width: '8px',
                },
                '&::-webkit-scrollbar-thumb': {
                    backgroundColor: '#1ABC9C',
                    borderRadius: '5px',
                },
            }}>
                <List sx={{}}>
                    {messages.map(({ id, primary, secondary, person }) => (
                        <React.Fragment key={id}>
                            <Card sx={{ mb: 1 }}>
                                <ListItemButton sx={{ position: 'relative', '&:hover .chat-icon': { opacity: 1 } }}
                                    onClick={goToChat}>
                                    <ListItemAvatar>
                                        <Avatar alt="Profile Picture" src={person} />
                                    </ListItemAvatar>
                                    <ListItemText primary={primary} 
                                    secondary={secondary.length > 50 ? `${secondary.slice(0, 70)} ...` : secondary} />
                                    <Box
                                        className="chat-icon"
                                        sx={{
                                            position: 'absolute',
                                            right: 16,
                                            top: '50%',
                                            transform: 'translateY(-50%)',
                                            opacity: 0,
                                            transition: 'opacity 0.3s',
                                            fontSize: 24,
                                            color: '#1ABC9C',
                                        }}
                                    >
                                        <Tooltip title="Chat">
                                            <Chat />
                                        </Tooltip>
                                    </Box>
                                </ListItemButton>
                            </Card>
                        </React.Fragment>
                    ))}
                </List>
            </Paper>
        </React.Fragment>
    );
}