server:
  port: 8761
spring:
  application:
    name: discovery-server
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

#Actuator with readiness and liveness
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
